services:
  - type: web
    name: sierra-back
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install --legacy-peer-deps && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true